### ISSUE TITLE
image on landing page does not redirect

### ISSUE THREAD

**Issue by kmkhami** [Debate-Land/monorepo#30]
First, hopefully I am not being too blunt. However, I find the whole landing page incredibly confusing. I have no idea what to do to actually start searching. I still have not figured out how to make a search. 

Specifically to this issue, the image on the landing page redirects to an error page (looks like Vercel NextJS default error). 

https://github.com/Debate-Land/monorepo/assets/15804464/f3f36d44-7cf4-4a00-a678-a9dca9728b66

**Comment by kmkhami** [comment]
Will close on merge of #34

**Comment by http-samc** [comment]
Fixed :)
