### ISSUE TITLE
is the dashboard complete? 

### ISSUE THREAD

**Issue by kmkhami** [Debate-Land/monorepo#31]
I feel like calling it a "dashboard" is a bit confusing. I assumed that dashboard would take me to the place where I could start making queries. 

But also, is it complete? It doesn't seem like I can do anything with it. 

![image](https://github.com/Debate-Land/monorepo/assets/15804464/2b5c8127-bf80-4a54-9c25-8429ffeaa937)

**Comment by http-samc** [comment]
No. It was active at one point but we changed our architecture (mongo to sql) and it wasn't coded up to our standards. It'll be redone with a proper gateway before 1.0.

**Comment by kmkhami** [comment]
Do you intend to disable it for now then?

**Comment by kmkhami** [comment]
I believe this should be re-opened and closed on merge of #36
