### ISSUE TITLE
errors clicking on search results

### ISSUE THREAD

**Issue by kmkhami** [Debate-Land/monorepo#32]
I still don't really understand how to use the app, but I get a bunch of errors when I try to click on search results

https://github.com/Debate-Land/monorepo/assets/15804464/75d47c84-aa1f-4649-95ea-d6a304018be9

**Comment by kmkhami** [comment]
I guess another thing is that the UI is not showing when/why requests error.

**Comment by http-samc** [comment]
This is a known issue ([reference](https://www.debate.land/known-issues)). I updated the ticket to include your demo video as it is quite helpful. Will look into handling RPC errors in the UI.
