### ISSUE TITLE
Is the code for the mobile app in this repo? 

### ISSUE THREAD

**Issue by kmkhami** [Debate-Land/monorepo#35]
Hey, I was looking through the `/apps` directory and I didn't see anything for the mobile app nor did I find it in the org. 

Are you guys working on that publicly? I got really curious about which native API's you were using.

**Comment by http-samc** [comment]
The app was for our old site, tournaments.tech. It isn't functional since the data apis have no overlap with Debate Land.

**Comment by http-samc** [comment]
We will be working on it publicly. There are a few upcoming features we need to work out on our roadmap for the web app. We do have to iron out some of the more advanced  features that use native device apis. Once we get out of beta on the web app we'll shift our focus to the mobile app and make our development of that public.
